name: Renovate

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2 AM
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.12
        env:
          token: ${{ secrets.RENOVATE_TOKEN }}
